# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-03-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=32)),
                ('adres', models.CharField(max_length=128)),
                ('bolum', models.CharField(max_length=64)),
                ('isim', models.CharField(max_length=32)),
                ('foto', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
