# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_programs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hakkimda',
            new_name='About',
        ),
    ]
