# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170402_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='aaa',
        ),
    ]
