# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170402_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aaa',
            new_name='Program',
        ),
    ]
